steps:
  - commands:
      - /usr/local/bin/dockerd --data-root /var/lib/docker --host=unix:///var/run/docker.sock > /dev/null 2>&1 &
      - while ! docker version > /dev/null 2>&1; do :; done
      - echo "$${FORGEJO_TOKEN}" | docker login --password-stdin --username $${FORGEJO_USER} ${CI_FORGE_URL##https://} > /dev/null 2>&1
      - /usr/local/bin/docker buildx create --name builder --use > /dev/null 2>&1
      - |
        /usr/local/bin/docker buildx build \
          --cache-from "access_key_id=$${HETZNER_ACCESS_KEY},bucket=$${HETZNER_OBJECT_STORAGE_CACHE_BUCKET},endpoint_url=$${HETZNER_OBJECT_STORAGE_CACHE_ENDPOINT_URL},region=$${HETZNER_OBJECT_STORAGE_CACHE_REGION},secret_access_key=$${HETZNER_SECRET_KEY},type=s3" \
          --cache-to "access_key_id=$${HETZNER_ACCESS_KEY},bucket=$${HETZNER_OBJECT_STORAGE_CACHE_BUCKET},endpoint_url=$${HETZNER_OBJECT_STORAGE_CACHE_ENDPOINT_URL},mode=max,region=$${HETZNER_OBJECT_STORAGE_CACHE_REGION},secret_access_key=$${HETZNER_SECRET_KEY},type=s3" \
          --output "type=image,push=true,rewrite-timestamp=true" \
          --platform "linux/amd64,linux/arm64" \
          --pull \
          --tag "${CI_FORGE_URL##https://}/${CI_REPO_OWNER}/backend:${CI_COMMIT_TAG##v}" \
          .
    environment:
      FORGEJO_TOKEN:
        from_secret: FORGEJO_TOKEN
      FORGEJO_USER:
        from_secret: FORGEJO_USER
      HETZNER_ACCESS_KEY:
        from_secret: HETZNER_ACCESS_KEY
      HETZNER_OBJECT_STORAGE_CACHE_BUCKET:
        from_secret: HETZNER_OBJECT_STORAGE_CACHE_BUCKET
      HETZNER_OBJECT_STORAGE_CACHE_ENDPOINT_URL:
        from_secret: HETZNER_OBJECT_STORAGE_CACHE_ENDPOINT_URL
      HETZNER_OBJECT_STORAGE_CACHE_REGION:
        from_secret: HETZNER_OBJECT_STORAGE_CACHE_REGION
      HETZNER_SECRET_KEY:
        from_secret: HETZNER_SECRET_KEY
    image: woodpeckerci/plugin-docker-buildx
    name: build-and-push
    privileged: true
when:
  - event: tag
